
name: Build LuaX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Lua
      uses: leafo/setup-lua@v1
      with:
        lua-version: "5.4"

    - name: Build LuaX
      run: |
        # Example: compile LuaX source
        mkdir -p build
        gcc -o build/luax src/*.c

    - name: Run Tests
      run: |
        # Example: run some basic LuaX tests
        ./build/luax test/test_script.lx

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: LuaX-${{ matrix.os }}
        path: build/
