name: LuaX Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install build tools
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          sudo apt-get update
          sudo apt-get install -y build-essential
        elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          brew install make
        elif [ "${{ matrix.os }}" = "windows-latest" ]; then
          choco install mingw -y
          choco install make -y
          echo "::add-path::C:\\tools\\mingw64\\bin"
        fi

    - name: Build LuaX
      run: make

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: LuaX-${{ matrix.os }}
        path: ./bin/luax  # replace with your compiled binary name
