name: LuaX Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up C compiler
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          choco install mingw
        fi

    - name: Build LuaX
      run: make

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: LuaX-${{ matrix.os }}
        path: ./bin/luax  # replace with your compiled binary name
